import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/modulo1">Módulo 1</Link>
            </li>
            <li>
              <Link href="/modulo2">Módulo 2</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
